export const inputsGenerarDecreto = [{
    nombre: "nDecreto",
    etiqueta: "N° decreto",
    tipo: "number",
    requerido: true,
    value: ""
}, {
    nombre: "actividad",
    etiqueta: "Nombre de la actividad",
    tipo: "text",
    requerido: true,
    value: ""
}, {
    nombre: "organizacion",
    etiqueta: "organizacion",
    tipo: "text",
    requerido: true,
    value: ""
}, {
    nombre: "rutOrganizacion",
    etiqueta: "rutOrganizacion",
    tipo: "text",
    requerido: true,
    value: ""
}, {
    nombre: "presidente",
    etiqueta: "presidente",
    tipo: "text",
    requerido: true,
    value: ""
}, {
    nombre: "rutPresidente",
    etiqueta: "rutPresidente",
    tipo: "text",
    requerido: true,
    value: ""
}, {
    nombre: "fechaInicio",
    etiqueta: "fechaInicio",
    tipo: "date",
    requerido: true,
    value: ""
}, {
    nombre: "horaInicio",
    etiqueta: "horaInicio",
    tipo: "time",
    requerido: true,
    value: ""
}, {
    nombre: "horaTermino",
    etiqueta: "horaTermino",
    tipo: "time",
    requerido: true,
    value: ""
}, {
    nombre: "ubicacion",
    etiqueta: "ubicacion",
    tipo: "text",
    requerido: true,
    value: ""
}]