POST http://localhost:10000/admin/requests/permisos-transitorios/18/aprobar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJydW4iOnsibnVtZXJvIjo0NDQ0NDQ0NCwiRFYiOiI0IiwidGlwbyI6IlJVTiJ9LCJuYW1lIjp7Im5vbWJyZXMiOlsiTWFyaWEiLCJDYXJtZW4iLCJEZSBsb3MgYW5nZWxlcyJdLCJhcGVsbGlkb3MiOlsiRGVsIHJpbyIsIkdvbnphbGV6Il19LCJpYXQiOjE3MzczNzQ3NTMsImV4cCI6MTczNzQwMzU1M30.c7i20pQXPLR15wL3dgYwZh7FVdwIojegthpuNU9kGHY