const initialValues = {
  name: '',
  rut: '',
  email: '',
  phone: '',
  orgName: '',
  orgRut: '',
  orgAddress: '',
  orgEmail: '',
  orgPhone: '',
  orgType: '',
  presidentName: '',
  presidentRut: '',
  presidentAddress: '',
  presidentEmail: '',
  presidentPhone: '',
  presidentPhone2: '',
  permissionName: '',
  permissionPlace: '',
  permissionStartDate: '',
  permissionStartTime: '',
  permissionEndDate: '',
  permissionEndTime: '',
  permissionAlcohol: '',
  permissionFood: '',
  permissionDescription: '',
  permissionPurpose: '',
};

export default initialValues;
